version: "3.7"

services:
  db_challenge:
    container_name: db_challenge
    image: mysql
    restart: always
    command: --innodb-use-native-aio=0
    volumes:
      - .docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nodedb
    ports:
      - 3306:3306
    networks:
      - challenge-network

  app_challenge:
    container_name: app_challenge
    build: .
    environment:
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=nodedb
      - DB_PORT=3306
      - DB_HOST=db_challenge
    depends_on:
      - db_challenge
    networks:
      - challenge-network

  nginx_challenge:
    container_name: nginx_challenge
    image: nginx:1.25.2-alpine
    ports:
      - 80:80
    volumes:
      - .docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../:/var/www
      - .docker/logs/nginx:/var/log/nginx
    depends_on:
      - app_challenge
    networks:
      - challenge-network

networks:
  challenge-network:
    driver: bridge
